from enum import Enum

from predefined.answer_predefined import Answers
from predefined.wording_model import Wording


class Acknowledgments(Enum):
    CHEERFUL = Wording('I see. Good. \N{smiling face with sunglasses}',
                       ['Alright. Let\'s move on.',
                        'Good. We can scratch this question off the list \N{check mark}',
                        'I get it. \N{thumbs up sign}',
                        'Ok \N{slightly smiling face}',
                        'OK, then let’s continue. \N{thumbs up sign}',
                        'You are doing great work. Let\'s  continue, shall we!',
                        'I get it, now. Good for you! \U0001f9e1',
                        'Got it. \U0001F44C',
                        'Good. Let\'s go ahead and keep going.',
                        'Excellent, many thanks!',
                        'Fantastic! \N{thumbs up sign}',
                        'Ok, let\'s have a look at the next one.',
                        'I see. Good for you! \N{thumbs up sign}',
                        'Terrific! Let\'s keep moving forward.',
                        'Nice going!  \N{slightly smiling face}',
                        'Based on this response, you seem to be in a good place.',
                        'Nice! \N{thumbs up sign}',
                        'Let’s see what follows. ',
                        'Outstanding. \N{slightly smiling face} Let’s jump to the next one.',
                        'Nice. \N{thumbs up sign}',
                        'Onwards, to the next question.  ',
                        'Cool. \N{grinning face with smiling eyes}',
                        'Happy to hear that! ',
                        'I’m glad that this is the case. \U0001F929',
                        'Got it! Jumping to the next question, then.',
                        'Awesome! \N{sparkling heart}',
                        'Good, good! Let’s move along to the next question.',
                        'Thanks! Let\'s proceed to the following question, shall we? \U0001F60D'])
    CHEERFUL_LAST = Wording('I see. Good. \N{smiling face with sunglasses}',
                       ['Good. We can scratch this question off the list \N{check mark}',
                        'I get it. \N{thumbs up sign}',
                        'Ok \N{slightly smiling face}',
                        'I get it, now. Good for you! \U0001f9e1',
                        'Got it. \U0001F44C',
                        'Excellent, many thanks!',
                        'Fantastic! \N{thumbs up sign}',
                        'I see. Good for you! \N{thumbs up sign}',
                        'Nice going!  \N{slightly smiling face}',
                        'Based on this response, you seem to be in a good place.',
                        'Nice! \N{thumbs up sign}',
                        'Nice. \N{thumbs up sign}',
                        'Cool. \N{grinning face with smiling eyes}',
                        'Happy to hear that! ',
                        'I’m glad that this is the case. \U0001F929',
                        'Awesome! \N{sparkling heart}'])
    NEUTRAL = Wording('I understand.',
                      ['I understand. I appreciate you taking the time to respond. \U0001F642',
                       'Thank you greatly for answering this!',
                       'Thank you for your openness! I\'m starting to know you better. \U0001F970',
                       'I understand & I appreciate your honest response.',
                       'Nice going till now! Let\'s move on to the next part. \U0001F44C',
                       'Honesty is always appreciated. Thank you for that!',
                       'Ok. I am curious about what your next response will be. \N{eyes}',
                       'Understood! \U0001F44C',
                       'Thank you for your answer. Let\'s try to continue.',
                       'I truly appreciate your answer. \U0001F642',
                       'I appreciate you answering all these questions. I think you\'re really cool \N{smiling face with sunglasses}',
                       'Yeah, sometimes it can be like this.',
                       'That is entirely understandable.',
                       'Thanks for this piece of info. Let\'s keep going.',
                       'I hope you know that you\'ve done a fantastic job up to this point! \U0001F44D',
                       'Yes, indeed, it may be like this at times. ',
                       'You\'re doing an outstanding job. Let\'s see what\'s next.',
                       'Yes, some days it can be a little difficult. ',
                       'Yeah, I get it. Some days it just does not work out as one would like. ',
                       'It\'s understandable that there are days when not everything is peachy. ',
                       'Indeed, some days are simply better than others. Our mission as humans is not to let the bad ones tilt the balance. ',
                       'It is understandable that you have some bad days. We all do.',
                       'Take each day at a time! Let\'s keep going.',
                       'Ok. I got it. It\'s good to express our feelings. Right?'])
    NEUTRAL_LAST = Wording('I understand.',
                      ['I understand. I appreciate you taking the time to respond. \U0001F642',
                       'Thank you greatly for answering this!',
                       'Thank you for your openness! I\'m starting to know you better. \U0001F970',
                       'I understand & I appreciate your honest response.',
                       'Honesty is always appreciated. Thank you for that!',
                       'Understood! \U0001F44C',
                       'I truly appreciate your answer. \U0001F642',
                       'I appreciate you answering all these questions. I think you\'re really cool \N{smiling face with sunglasses}',
                       'Yeah, sometimes it can be like this.',
                       'That is entirely understandable.',
                       'Yes, indeed, it may be like this at times. ',
                       'Yes, some days it can be a little difficult. ',
                       'Yeah, I get it. Some days it just does not work out as one would like. ',
                       'It\'s understandable that there are days when not everything is peachy. ',
                       'Indeed, some days are simply better than others. Our mission as humans is not to let the bad ones tilt the balance. ',
                       'It is understandable that you have some bad days. We all do.',
                       'Ok. I got it. It\'s good to express our feelings. Right?'])
    SYMPATHETIC = Wording('I understand. This must be challenging. \U0001F917',
                          ['I hear you. When life hands you lemons, sometimes it can feel like you simply can\'t make lemonade. ',
                           'I must say, nearly everyone faces difficulties at some point in their lives.',
                           'I get what you mean. Don\'t forget  that I care about your well-being. Let\'s try to continue. \U0001F970',
                           'I understand. I am here to walk you through it. Come on, let\'s keep going!',
                           'I see what you\'re saying. You\'re doing a fantastic job answering all of these questions.',
                           'I get it. Nearly everyone goes through adversity in their life.',
                           'Ah! You have my whole attention. I am here for you! Let\'s try to answer another question. \U0001F917',
                           'Yes, I see what you mean. It has to be challenging. Try to keep going.',
                           'This must be challenging, but I\'m in your corner. \U0001F917',
                           'In my opinion, you\'re doing a great job answering each of these questions.',
                           'Thank you for this response! I appreciate the time you spend with me. ',
                           'I can only imagine how distressing it must be for you! I am in your corner. Let\'s try to continue.',
                           'I think the way you\'re answering each of these questions is great. \U0001F60D',
                           'Yes, I get it. It must be difficult. You\'re fantastic! Keep going.',
                           'I see how it can be like that. Really appreciative that you take the time to answer all these questions. Let\'s continue.',
                           'It\'s wonderful to see you answering all of these, at times, difficult questions. ',
                           'May I say? In my opinion you rule!',
                           'Your response matters greatly to me. \U0001F917',
                           'Although it can be discouraging at times, we always have to try to get up and move forward.',
                           'I know it isn\'t easy to deal with stuff like this. Approach it day by day! \U0001F617',
                           'Even if it does not seem like it at the moment, it helps to share and talk about these difficulties. \U0001F60C',
                           'Thank you for opening up and sharing!',
                           'Ah! That appears to be difficult. Thank you for your openness.',
                           'I see! Not every day is perfect. But, you answered perfectly \N{thumbs up sign}',
                           'I get it! Maybe this will help: you are doing great! ',
                           'I see what you\'re saying. Being a human might be challenging at times, but you\'re an amazing one.'])
    SYMPATHETIC_LAST = Wording('I understand. This must be challenging. \U0001F917',
                          ['I hear you. When life hands you lemons, sometimes it can feel like you simply can\'t make lemonade. ',
                           'I must say, nearly everyone faces difficulties at some point in their lives.',
                           'I see what you\'re saying. You\'re doing a fantastic job answering all of these questions.',
                           'I get it. Nearly everyone goes through adversity in their life.',
                           'This must be challenging, but I\'m in your corner. \U0001F917',
                           'In my opinion, you\'re doing a great job answering each of these questions.',
                           'Thank you for this response! I appreciate the time you spend with me. ',
                           'I think the way you\'re answering each of these questions is great. \U0001F60D',
                           'Yes, I get it. It must be difficult. You\'re fantastic! Keep going.',
                           'It\'s wonderful to see you answering all of these, at times, difficult questions. ',
                           'May I say? In my opinion you rule!',
                           'Your response matters greatly to me. \U0001F917',
                           'Although it can be discouraging at times, we always have to try to get up and move forward.',
                           'I know it isn\'t easy to deal with stuff like this. Approach it day by day! \U0001F617',
                           'Even if it does not seem like it at the moment, it helps to share and talk about these difficulties. \U0001F60C',
                           'Thank you for opening up and sharing!',
                           'Ah! That appears to be difficult. Thank you for your openness.',
                           'I see! Not every day is perfect. But, you answered perfectly \N{thumbs up sign}',
                           'I get it! Maybe this will help: you are doing great! ',
                           'I see what you\'re saying. Being a human might be challenging at times, but you\'re an amazing one.'])
    CONCERNED = Wording('Thank you for sharing this with me! I realize  it isn\'t easy. \U0001F614',
                        ['Thank you for being so open about this matter!',
                         'Surely, this is a tough subject to approach. Your response is greatly appreciated.',
                         'I am sorry you are going through this. \N{crying face}',
                         'I see. Keep in mind that all problems have solutions. Let\'s try to continue!',
                         'I am here for you!',
                         'That has to be really difficult. Thank you for sharing!',
                         'I can only imagine how difficult this must be, but I am here for you.',
                         'This must be very tough for you, but I am here to see you through it. Let\'s try to continue.',
                         'You are not alone. I am here. Thank you for your answer!',
                         'Thank you for sharing this with me! I am here to help to the best of my knowledge. \U0001F642',
                         'I understand, it must be very distressing. Thank you for writing openly about it!  ',
                         'Oh, wow, that must be very hard for you to share with me. Thank you for that!',
                         'I am so sorry you are going through this. Thank you for being so open.',
                         'I understand. I really wish I could make it better. \U0001F917',
                         'I can see how that would be very difficult. Thank you for trusting me with this!',
                         'That sounds really challenging. Thanks for opening up to me!',
                         'Please know that I am truly sorry for what you are going through. When you\'re ready, we can go on to the next question on our list.',
                         'It must be difficult to discuss. Thank you for sharing!',
                         'I understand that you are going through a difficult time.',
                         'Being so open about it means you rock!',
                         'I\'m here for you! \U0001F917',
                         'Thank you for sharing! I am learning so much from you! \U0001F60D',
                         'I\'m sorry you have to deal with this! \N{worried face}',
                         'Although I understand how difficult it must be to discuss this subject, I applaud your effort. \U0001F44F',
                         'I can totally imagine how hard it must be to be confronted with this so often. \U0001F614',
                         'I can imagine how having to deal with this on a nearly daily basis can be really tough.',
                         'This is a difficult situation and I think you\'re showing a lot of strength by talking to me about it. ',
                         'It sounds like the last couple of weeks were extremely trying. Thank you for sharing this with me! \U0001F917',
                         'I\'d say you\'re incredible for being open about it. I am aware that the subject is difficult. Thank you very much for responding! \U0001F497',
                         'Thank you for opening up to me! This is a safe place! ',
                         'Thank you. Discussing difficult situations is important when they happen. When it\'s okay with you, we can try to keep going.',
                         'It\'s been a difficult couple of weeks, hasn\'t it? ',
                         'What a difficult experience that must have been for you! \U0001F917',
                         'I wish you didn\'t have to go through that.',
                         'How hard... Thanks for being honest! I\'m very sad this is happening. \N{worried face}'])
    CONCERNED_LAST = Wording('Thank you for sharing this with me! I realize  it isn\'t easy. \U0001F614',
                        ['Thank you for being so open about this matter!',
                         'Surely, this is a tough subject to approach. Your response is greatly appreciated.',
                         'I am sorry you are going through this. \N{crying face}',
                         'I am here for you! \U0001F917',
                         'That has to be really difficult. Thank you for sharing!',
                         'I can only imagine how difficult this must be, but I am here for you.',
                         'You are not alone. I am here. Thank you for your answer!',
                         'Thank you for sharing this with me! I am here to help to the best of my knowledge. \U0001F642',
                         'I understand, it must be very distressing. Thank you for writing openly about it!  ',
                         'Oh, wow, that must be very hard for you to share with me. Thank you for that!',
                         'I am so sorry you are going through this. Thank you for being so open.',
                         'I understand. I really wish I could make it better. \U0001F917',
                         'I can see how that would be very difficult. Thank you for trusting me with this!',
                         'That sounds really challenging. Thanks for opening up to me!',
                         'Please know that I am truly sorry for what you are going through. When you\'re ready, we can go on to the next question on our list.',
                         'It must be difficult to discuss. Thank you for sharing!',
                         'I understand that you are going through a difficult time.',
                         'Being so open about it means you rock!',
                         'I\'m here for you!',
                         'Thank you for sharing! I am learning so much from you! \U0001F60D',
                         'I\'m sorry you have to deal with this! \N{worried face}',
                         'Although I understand how difficult it must be to discuss this subject, I applaud your effort. \U0001F44F',
                         'I can totally imagine how hard it must be to be confronted with this so often. \U0001F614',
                         'I can imagine how having to deal with this on a nearly daily basis can be really tough.',
                         'This is a difficult situation and I think you\'re showing a lot of strength by talking to me about it. ',
                         'It sounds like the last couple of weeks were extremely trying. Thank you for sharing this with me! \U0001F917',
                         'I\'d say you\'re incredible for being open about it. I am aware that the subject is difficult. Thank you very much for responding! \U0001F497',
                         'Thank you for opening up to me! This is a safe place! ',
                         'Thank you. Discussing difficult situations is important when they happen. When it\'s okay with you, we can try to keep going.',
                         'It\'s been a difficult couple of weeks, hasn\'t it? ',
                         'What a difficult experience that must have been for you! \U0001F917',
                         'I wish you didn\'t have to go through that.',
                         'How hard... Thanks for being honest! I\'m very sad this is happening. \N{worried face}'])
    SYMPATHETIC_PHQ_9 = Wording('Thank you for your openness! It means a lot to me. It is important that you contact a mental health specialist to discuss these thoughts. If you are feeling overwhelmed and need someone to talk to right now, please consider reaching out to a suicide helpline [Romanian National Suicide Prevention Lifeline: +40 800801200, www.antisuicid.ro; international Suicide Prevention Lifelines: https://blog.opencounseling.com/suicide-hotlines/] which provides free & confidential support. Remember that though the world is full of suffering, it is also full of ways to overcome it. I hope it is OK to continue with our interaction. Your well-being is the most important thing to me. \U0001F917', [])
    CONCERNED_PHQ_9 = Wording('This must be very difficult! It is important that you try to reach a mental health specialist to talk about your feelings. If you are feeling overwhelmed and need someone to talk to right now, please consider reaching out to a suicide helpline [Romanian National Suicide Prevention Lifeline: +40 800801200, www.antisuicid.ro; international Suicide Prevention Lifelines: https://blog.opencounseling.com/suicide-hotlines/] which provides free & confidential support. Remember that though the world is full of suffering, it is also full of ways to overcome it. I hope it is OK to continue with our interaction. Your well-being is the most important thing to me.', [])
    SYMPATHETIC_PCL_5 = Wording('I am sorry that you have to go through this. It is important that you see a mental health specialist to discuss how you are feeling. If you are feeling overwhelmed and need someone to talk to right now, please consider reaching out to a suicide helpline [Romanian National Suicide Prevention Lifeline: +40 800801200, www.antisuicid.ro; international Suicide Prevention Lifelines: https://blog.opencounseling.com/suicide-hotlines/] which provides free & confidential support. Remember that you are not alone in this. I hope it is OK, if I continue our discussion. Your safety and health are my greatest concern. \U0001F917', [])
    CONCERNED_PCL_5 = Wording('This must be very difficult! It is important that you contact a mental health specialist to discuss how you are feeling. If you are feeling overwhelmed and need someone to talk to right now, please consider reaching out to a suicide helpline [Romanian National Suicide Prevention Lifeline: +40 800801200, www.antisuicid.ro; international Suicide Prevention Lifelines: https://blog.opencounseling.com/suicide-hotlines/] which provides free & confidential support. Remember that you are not alone in this. I hope it is OK, if I continue our discussion. Your safety and health are my greatest concern. \U0001F9E1', [])


class AcknowledgmentSets(Enum):
    COMMON = {
        Answers.DAY_FREQUENCY_03.value.get_item_by_ordinal(0).code: Acknowledgments.CHEERFUL.value,
        Answers.DAY_FREQUENCY_03.value.get_item_by_ordinal(1).code: Acknowledgments.NEUTRAL.value,
        Answers.DAY_FREQUENCY_03.value.get_item_by_ordinal(2).code: Acknowledgments.SYMPATHETIC.value,
        Answers.DAY_FREQUENCY_03.value.get_item_by_ordinal(3).code: Acknowledgments.CONCERNED.value,
        Answers.INTENSITY_04.value.get_item_by_ordinal(0).code: Acknowledgments.CHEERFUL.value,
        Answers.INTENSITY_04.value.get_item_by_ordinal(1).code: Acknowledgments.NEUTRAL.value,
        Answers.INTENSITY_04.value.get_item_by_ordinal(2).code: None,
        Answers.INTENSITY_04.value.get_item_by_ordinal(3).code: Acknowledgments.SYMPATHETIC.value,
        Answers.INTENSITY_04.value.get_item_by_ordinal(4).code: Acknowledgments.CONCERNED.value,
    }
    CAREFUL = {
        Answers.DAY_FREQUENCY_03.value.get_item_by_ordinal(0).code: Acknowledgments.CHEERFUL.value,
        Answers.DAY_FREQUENCY_03.value.get_item_by_ordinal(1).code: Acknowledgments.SYMPATHETIC_PHQ_9.value,
        Answers.DAY_FREQUENCY_03.value.get_item_by_ordinal(2).code: Acknowledgments.CONCERNED_PHQ_9.value,
        Answers.DAY_FREQUENCY_03.value.get_item_by_ordinal(3).code: Acknowledgments.CONCERNED_PHQ_9.value,
        Answers.INTENSITY_04.value.get_item_by_ordinal(0).code: Acknowledgments.CHEERFUL.value,
        Answers.INTENSITY_04.value.get_item_by_ordinal(1).code: Acknowledgments.SYMPATHETIC_PCL_5.value,
        Answers.INTENSITY_04.value.get_item_by_ordinal(2).code: None,
        Answers.INTENSITY_04.value.get_item_by_ordinal(3).code: Acknowledgments.CONCERNED_PCL_5.value,
        Answers.INTENSITY_04.value.get_item_by_ordinal(4).code: Acknowledgments.CONCERNED_PCL_5.value,
    }
    COMMON_LAST = {
        Answers.DAY_FREQUENCY_03.value.get_item_by_ordinal(0).code: Acknowledgments.CHEERFUL_LAST.value,
        Answers.DAY_FREQUENCY_03.value.get_item_by_ordinal(1).code: Acknowledgments.NEUTRAL_LAST.value,
        Answers.DAY_FREQUENCY_03.value.get_item_by_ordinal(2).code: Acknowledgments.SYMPATHETIC_LAST.value,
        Answers.DAY_FREQUENCY_03.value.get_item_by_ordinal(3).code: Acknowledgments.CONCERNED_LAST.value,
        Answers.INTENSITY_04.value.get_item_by_ordinal(0).code: Acknowledgments.CHEERFUL_LAST.value,
        Answers.INTENSITY_04.value.get_item_by_ordinal(1).code: Acknowledgments.NEUTRAL_LAST.value,
        Answers.INTENSITY_04.value.get_item_by_ordinal(2).code: None,
        Answers.INTENSITY_04.value.get_item_by_ordinal(3).code: Acknowledgments.SYMPATHETIC_LAST.value,
        Answers.INTENSITY_04.value.get_item_by_ordinal(4).code: Acknowledgments.CONCERNED_LAST.value,
    }
    CAREFUL_LAST = {
        Answers.DAY_FREQUENCY_03.value.get_item_by_ordinal(0).code: Acknowledgments.CHEERFUL_LAST.value,
        Answers.DAY_FREQUENCY_03.value.get_item_by_ordinal(1).code: Acknowledgments.SYMPATHETIC_PHQ_9.value,
        Answers.DAY_FREQUENCY_03.value.get_item_by_ordinal(2).code: Acknowledgments.CONCERNED_PHQ_9.value,
        Answers.DAY_FREQUENCY_03.value.get_item_by_ordinal(3).code: Acknowledgments.CONCERNED_PHQ_9.value,
        Answers.INTENSITY_04.value.get_item_by_ordinal(0).code: Acknowledgments.CHEERFUL_LAST.value,
        Answers.INTENSITY_04.value.get_item_by_ordinal(1).code: Acknowledgments.SYMPATHETIC_PCL_5.value,
        Answers.INTENSITY_04.value.get_item_by_ordinal(2).code: None,
        Answers.INTENSITY_04.value.get_item_by_ordinal(3).code: Acknowledgments.CONCERNED_PCL_5.value,
        Answers.INTENSITY_04.value.get_item_by_ordinal(4).code: Acknowledgments.CONCERNED_PCL_5.value,
    }
